package com.oraro.panoramicagriculture.data.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.util.Log;

import org.greenrobot.greendao.AbstractDaoMaster;
import org.greenrobot.greendao.database.StandardDatabase;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseOpenHelper;
import org.greenrobot.greendao.identityscope.IdentityScopeType;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * Master of DAO (schema version 1): knows all DAOs.
 */
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(Database db, boolean ifNotExists) {
        AnAcreLandDao.createTable(db, ifNotExists);
        CropsDao.createTable(db, ifNotExists);
        CropsResultsDao.createTable(db, ifNotExists);
        DCEntityDao.createTable(db, ifNotExists);
        DCPurchaseDataDao.createTable(db, ifNotExists);
        DistributionDao.createTable(db, ifNotExists);
        FarmEntityDao.createTable(db, ifNotExists);
        FarmFieldDao.createTable(db, ifNotExists);
        FieldBorderDao.createTable(db, ifNotExists);
        HarvestListDao.createTable(db, ifNotExists);
        NeedListDao.createTable(db, ifNotExists);
        PlantHistoryDao.createTable(db, ifNotExists);
        PreCropsDao.createTable(db, ifNotExists);
        PurchaseOrderDao.createTable(db, ifNotExists);
        PurchasePlusAmountDao.createTable(db, ifNotExists);
        PurchaseProductDao.createTable(db, ifNotExists);
        PurchaseRelativeDao.createTable(db, ifNotExists);
        PurchaseResultsDao.createTable(db, ifNotExists);
        PurchasingPointDao.createTable(db, ifNotExists);
        PushMessageJsonDao.createTable(db, ifNotExists);
        RegionSaleInfoDao.createTable(db, ifNotExists);
        SubscriptionInfoDao.createTable(db, ifNotExists);
        UserEntityDao.createTable(db, ifNotExists);
        VFCropsDao.createTable(db, ifNotExists);
    }

    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(Database db, boolean ifExists) {
        AnAcreLandDao.dropTable(db, ifExists);
        CropsDao.dropTable(db, ifExists);
        CropsResultsDao.dropTable(db, ifExists);
        DCEntityDao.dropTable(db, ifExists);
        DCPurchaseDataDao.dropTable(db, ifExists);
        DistributionDao.dropTable(db, ifExists);
        FarmEntityDao.dropTable(db, ifExists);
        FarmFieldDao.dropTable(db, ifExists);
        FieldBorderDao.dropTable(db, ifExists);
        HarvestListDao.dropTable(db, ifExists);
        NeedListDao.dropTable(db, ifExists);
        PlantHistoryDao.dropTable(db, ifExists);
        PreCropsDao.dropTable(db, ifExists);
        PurchaseOrderDao.dropTable(db, ifExists);
        PurchasePlusAmountDao.dropTable(db, ifExists);
        PurchaseProductDao.dropTable(db, ifExists);
        PurchaseRelativeDao.dropTable(db, ifExists);
        PurchaseResultsDao.dropTable(db, ifExists);
        PurchasingPointDao.dropTable(db, ifExists);
        PushMessageJsonDao.dropTable(db, ifExists);
        RegionSaleInfoDao.dropTable(db, ifExists);
        SubscriptionInfoDao.dropTable(db, ifExists);
        UserEntityDao.dropTable(db, ifExists);
        VFCropsDao.dropTable(db, ifExists);
    }

    /**
     * WARNING: Drops all table on Upgrade! Use only during development.
     * Convenience method using a {@link DevOpenHelper}.
     */
    public static DaoSession newDevSession(Context context, String name) {
        Database db = new DevOpenHelper(context, name).getWritableDb();
        DaoMaster daoMaster = new DaoMaster(db);
        return daoMaster.newSession();
    }

    public DaoMaster(SQLiteDatabase db) {
        this(new StandardDatabase(db));
    }

    public DaoMaster(Database db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(AnAcreLandDao.class);
        registerDaoClass(CropsDao.class);
        registerDaoClass(CropsResultsDao.class);
        registerDaoClass(DCEntityDao.class);
        registerDaoClass(DCPurchaseDataDao.class);
        registerDaoClass(DistributionDao.class);
        registerDaoClass(FarmEntityDao.class);
        registerDaoClass(FarmFieldDao.class);
        registerDaoClass(FieldBorderDao.class);
        registerDaoClass(HarvestListDao.class);
        registerDaoClass(NeedListDao.class);
        registerDaoClass(PlantHistoryDao.class);
        registerDaoClass(PreCropsDao.class);
        registerDaoClass(PurchaseOrderDao.class);
        registerDaoClass(PurchasePlusAmountDao.class);
        registerDaoClass(PurchaseProductDao.class);
        registerDaoClass(PurchaseRelativeDao.class);
        registerDaoClass(PurchaseResultsDao.class);
        registerDaoClass(PurchasingPointDao.class);
        registerDaoClass(PushMessageJsonDao.class);
        registerDaoClass(RegionSaleInfoDao.class);
        registerDaoClass(SubscriptionInfoDao.class);
        registerDaoClass(UserEntityDao.class);
        registerDaoClass(VFCropsDao.class);
    }

    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }

    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }

    /**
     * Calls {@link #createAllTables(Database, boolean)} in {@link #onCreate(Database)} -
     */
    public static abstract class OpenHelper extends DatabaseOpenHelper {
        public OpenHelper(Context context, String name) {
            super(context, name, SCHEMA_VERSION);
        }

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(Database db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }

    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name) {
            super(context, name);
        }

        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(Database db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

}
