package com.oraro.panoramicagriculture.data.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.oraro.panoramicagriculture.data.entity.PurchasePlusAmount;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PURCHASE_PLUS_AMOUNT".
*/
public class PurchasePlusAmountDao extends AbstractDao<PurchasePlusAmount, Long> {

    public static final String TABLENAME = "PURCHASE_PLUS_AMOUNT";

    /**
     * Properties of entity PurchasePlusAmount.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PoNO = new Property(1, String.class, "poNO", false, "PO_NO");
        public final static Property Content = new Property(2, String.class, "content", false, "CONTENT");
        public final static Property Percnet = new Property(3, double.class, "percnet", false, "PERCNET");
        public final static Property Amonut = new Property(4, double.class, "amonut", false, "AMONUT");
    };


    public PurchasePlusAmountDao(DaoConfig config) {
        super(config);
    }
    
    public PurchasePlusAmountDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PURCHASE_PLUS_AMOUNT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"PO_NO\" TEXT," + // 1: poNO
                "\"CONTENT\" TEXT," + // 2: content
                "\"PERCNET\" REAL NOT NULL ," + // 3: percnet
                "\"AMONUT\" REAL NOT NULL );"); // 4: amonut
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PURCHASE_PLUS_AMOUNT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PurchasePlusAmount entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String poNO = entity.getPoNO();
        if (poNO != null) {
            stmt.bindString(2, poNO);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(3, content);
        }
        stmt.bindDouble(4, entity.getPercnet());
        stmt.bindDouble(5, entity.getAmonut());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PurchasePlusAmount entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String poNO = entity.getPoNO();
        if (poNO != null) {
            stmt.bindString(2, poNO);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(3, content);
        }
        stmt.bindDouble(4, entity.getPercnet());
        stmt.bindDouble(5, entity.getAmonut());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PurchasePlusAmount readEntity(Cursor cursor, int offset) {
        PurchasePlusAmount entity = new PurchasePlusAmount( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // poNO
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // content
            cursor.getDouble(offset + 3), // percnet
            cursor.getDouble(offset + 4) // amonut
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PurchasePlusAmount entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPoNO(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setContent(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPercnet(cursor.getDouble(offset + 3));
        entity.setAmonut(cursor.getDouble(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PurchasePlusAmount entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PurchasePlusAmount entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
